### ISSUE TITLE
Please add a license file, a screen shot, and consider renaming the repo to something unique.

### ISSUE THREAD

**Issue by unixorn** [jmg-duarte/flux-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

I also prefer to add themes with screen shots in their readme so that users can see what they look like without having to install them.

Finally, please add a license file, some people won't use any code that doesn't have a license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by jmg-duarte** [comment]
Hey Joe! Thank you for your interest in my theme!

I've reviewed the repo and applied some changes, let me know if is there is anything missing!

**Comment by jmg-duarte** [comment]
I've updated the repo, I think the only thing missing right now are screenshots, which I will add ASAP

**Comment by jmg-duarte** [comment]
I've added a screenshot, I don't think more are needed since everything the theme currently provides is there.
